### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mahmednabil109** [MohamedShetewi/stomp-in-go#2]
## First some conventions:
   - file names are expected to be lowercase with underscores (_snake_case_)
   - it's also expected to separate the responsibilities of the code into packages (_single responsibility principle_)
 
## Code Review:
- it's slightly not clear what is the responsibility of `connectHandler` func.
  https://github.com/MohamedShetewi/stomp-in-go/blob/a5b2284ceec83625b74e732bb14453e5aab23c78/CommandHandler.go#L15
- go compiler already dereferences the pointers so you can use `client.outHB`.
 https://github.com/MohamedShetewi/stomp-in-go/blob/a5b2284ceec83625b74e732bb14453e5aab23c78/CommandHandler.go#L29-L31

- using named return variables is considered a good practice (sometimes :)), but it's better to unify the convention used in the code. it also can cause some confusion, like
  https://github.com/MohamedShetewi/stomp-in-go/blob/a5b2284ceec83625b74e732bb14453e5aab23c78/Decoder.go#L32
 when using a ref value like a map you should allocate memory for it first _(using make)_ before using it. using named return vars could result in forgetting this step.
   https://github.com/MohamedShetewi/stomp-in-go/blob/a5b2284ceec83625b74e732bb14453e5aab23c78/Decoder.go#L39
 ERR: this will result in accessing nil value.

- this is fine -ig-, but depending on the frame size it should be faster to use a [Buffer](https://pkg.go.dev/bytes#Buffer) instead of concatinating in a string (same as String vs StringBuilder in java). (tbh i don't know how strings is implemented in go but strong guess it's immutable so the concat operation will be costy).
   https://github.com/MohamedShetewi/stomp-in-go/blob/a5b2284ceec83625b74e732bb14453e5aab23c78/Frame.go#L29-L41
- this is not needed as `Slice` is already a reference value (it's a struct that contains data about an underlaying arr and a ref to that array so when you send it be value it will copy the pointer to the arr not the arr so using `*[]` is not needed [more info read this](https://go.dev/blog/slices-intro))
   https://github.com/MohamedShetewi/stomp-in-go/blob/a5b2284ceec83625b74e732bb14453e5aab23c78/utils.go#L3
   also here it's not need to dereference the pointer, also `any` should work fine ,`comparable` has no meaning here
      https://github.com/MohamedShetewi/stomp-in-go/blob/a5b2284ceec83625b74e732bb14453e5aab23c78/utils.go#L5

### TODO: review Server.go

**Comment by MohamedShetewi** [comment]
> * it's slightly not clear what is the responsibility of `connectHandler` func.

The `connectHandler` is the function that is responsible for handling the `Connect` Command. Command is a part of frames that is being exchanged between the client and the server.
